version: "3.9"

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - scylladb-1
      - scylladb-2
      - scylladb-3
    command: ["./wait-for-it.sh", "scylladb-1:9041", "--", "./orderbook-api-rs"]
    environment:
      DATABASE_URL: scylladb-1:9041,scylladb-2:9042,scylladb-3:9043
      RUST_LOG: orderbook_api_rs=debug

  scylladb-1:
    image: scylladb/scylla:5.1
    ports:
      - 9041:9042
    restart: unless-stopped
    command: --seeds=scylladb-1,scylladb-2,scylladb-3 --cpuset 0 --smp 1 --memory 2048M
    volumes:
      - scylladb-1-data:/var/lib/scylla

  scylladb-2:
    image: scylladb/scylla:5.1
    ports:
      - 9042:9042
    restart: unless-stopped
    command: --seeds=scylladb-1,scylladb-2,scylladb-3 --cpuset 1 --smp 1 --memory 2048M
    volumes:
      - scylladb-2-data:/var/lib/scylla

  scylladb-3:
    image: scylladb/scylla:5.1
    ports:
      - 9043:9042
    restart: unless-stopped
    command: --seeds=scylladb-1,scylladb-2,scylladb-3 --cpuset 2 --smp 1 --memory 2048M
    volumes:
      - scylladb-3-data:/var/lib/scylla

volumes:
  scylladb-1-data:
  scylladb-2-data:
  scylladb-3-data:
