version: "3.9"

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://main:main@postgres/main
      DATABASE_CONNECTION_POOL_SIZE: 5
      RUST_LOG: orderbook_api_rs=debug
